<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>servo_controller</name>
  <version>0.0.0</version>
  <description>ROS 2 package for Kinova arm servo control via PCA9685 I2C bridge</description>
  <maintainer email="1760298213@qq.com">1760298213</maintainer>
  <license>Apache-2.0</license>

  <buildtool_depend>ament_python</buildtool_depend>
  <depend>rclpy</depend>  <!-- ROS 2 Python核心依赖 -->

  <!-- 声明第三方Python依赖（如kortex-api） -->
  <exec_depend>python3-kortex-api</exec_depend>
  <export>
    <build_type>ament_python</build_type>
  </export>
</package>
